### ISSUE TITLE
Pinned.fromSize and onTap not working

### ISSUE THREAD

**Issue by giacomok** [AdobeXD/xd-to-flutter-plugin#100]
Hi, I have this Pinned.fromSize:

    Pinned.fromSize(
      bounds: Rect.fromLTWH(29.0, 11.0, 42.0, 23.0),
      size: Size(100.0, 44.0),
      fixedWidth: true,
      fixedHeight: true,
      child:
          // Adobe XD layer: 'Sign in' (text)
          Text(
        'Login',
        style: TextStyle(
          fontFamily: 'Poppins-Medium',
          fontSize: 16,
          color: const Color(0xffffffff),
        ),
        textAlign: TextAlign.center,
      ),
    ),

I need to implement `onTap` on Login Text. I tried with `InkWell` and `GestureDetector` (with `Text` as child) without success.  
How can I handle this?

**Comment by connelevalsam** [comment]
did you fix this?

I'm having the same error

**Comment by gskinner** [comment]
We use GestureDetector in PageLink and for onTap params, and it works as expected (at least here). Any chance you could provide more info?

**Comment by gskinner** [comment]
Closing due to lack of detail. Please feel free to reopen with more information.
