### ISSUE TITLE
Please provide a null-safe version of this library ASAP

### ISSUE THREAD

**Issue by Gopinathp** [AdobeXD/xd-to-flutter-plugin#103]
Please publish a null-safe version of this library. This has become a blocker for my null-safety migration of my production code. 

_We love to hear your ideas, but we need your help. Please take a few minutes to fill out the information below, and provide a concise, descriptive title._

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gskinner** [comment]
Hi @Gopinathp - I've just pushed a commit that implements null-safety in the `adobe_xd` package, and we will hopefully be publishing it to pubdev in the next few days after a bit more testing.

I would love to have you or anyone else who is interested take a look at it and/or give it a test.

Commit: bd43db0e056a375dfbba114da9a83478268e238e

**Comment by gskinner** [comment]
I've also added more robust checks for pubspec.yaml to try to inform users if they've enabled null safety without appropriate support.

**Comment by gskinner** [comment]
Quick note: Added support for null safety in Grid export as well via: b930676fd3edf5bd26b9d4bfa50d750286135f1c

**Comment by gskinner** [comment]
Live in v2.0.0
