### ISSUE TITLE
XD to Flutter plugin: no responsiveness?

### ISSUE THREAD

**Issue by mikeminton** [AdobeXD/xd-to-flutter-plugin#104]
## Bug Description

When loading exported dart files, the responsiveness does not exist - it is almost like all of the elements are fixed sizes and fixed positions on the newly painted widget/screen.

So when resizing windows/or different phones none of the items respond to the adjustment.

## Versions:

 - OS: Windows 10 - 64 Bit
 - XD: 38.0.12.13
 - plugin: 1.1.0
 - Flutter: lastest within Android Studio

**Comment by gskinner** [comment]
It's hard to help without more details. It sounds like something near the top of your XD or Flutter tree has responsive layout disabled. Did you take a look at the example? Responsive layout should definitely work.

Closing this, but feel free to reopen if you can provide details.
