### ISSUE TITLE
HEEEELP

### ISSUE THREAD

**Issue by MURSHIG** [AdobeXD/xd-to-flutter-plugin#105]
How to use Pinned.fromSize like button

**Comment by gskinner** [comment]
I would recommend using Pinned.fromPins in most cases. Pinned.fromSize calculates pins from a set of layout flags (ex. pinLeft, fixedWidth, etc), the nominal size of a parent container, and the nominal bounds (size and position) of the child within that parent. It's mostly intended for output from a pre-existing design.

`Pinned.fromPins` is (imho) easier to understand, and doesn't rely on semi-arbitrary "starting" dimensions. In fact, the next version of the plugin is switching entirely to using `Pinned.fromPins`.

Let me know if you have more specific questions.
