### ISSUE TITLE
everything is off, layout wise

### ISSUE THREAD

**Issue by trailerzone** [AdobeXD/xd-to-flutter-plugin#108]
I am not sure how this happens, but I've converted the layout and it probably should be based off of mediaquery when generating the code, because nothing in the app is lining up. everything is off and I don't even know where to begin when adjusting the code to fit within the screen and where it is supposed to be.

---

## Bug Description

A clear and concise description of what the bug is. Does it happen with a specific file, artboard, or element? Can it be reproduced with a simpler case? Issues with descriptions such as "Can't export my file" don't provide us any information to work from, and will be closed.

## To Reproduce

Specific steps to reproduce the behavior.

## Sample XD File or Screenshots

If possible, add a link to an XD file that demonstrates the problem in the simplest way possible (ie. isolate just the artboard and layer that is causing the problem). If applicable, add screenshots to help explain your problem.

## Console Output

Open the Developer Console in menu > plugins > developer, and provide any errors that are generated as part of the issue.

## Versions:

 - OS: [e.g. MacOS 10.15.1]
 - XD: [e.g. 29]
 - plugin: [e.g. 1.0.0] (near the bottom of the panel)
 - Flutter: [e.g. stable 1.20.0]

**Comment by gskinner** [comment]
Closing for lack of any details.
