### ISSUE TITLE
make options for install the plug in manually without using the adobe XD 

### ISSUE THREAD

**Issue by AbodAmar** [AdobeXD/xd-to-flutter-plugin#116]
_We love to hear your ideas, but we need your help. Please take a few minutes to fill out the information below, and provide a concise, descriptive title._

**Is your feature request related to a problem? Please describe.**
the problem is I can't reach to the plug in through the XD APPLICATION that because a lot of people use cracked of adobe products which come with internet blocker that cut the internet from any abode product  
![Screenshot 2021-06-16 154046](https://user-images.githubusercontent.com/40468933/122220667-38136980-ceb9-11eb-86bb-442348872b19.jpg)

**Describe the solution you'd like**
the solution is simple just upload the plug-in  in .XDX format so that we can install in manually 
![Screenshot 2021-06-16 155636](https://user-images.githubusercontent.com/40468933/122223072-84f83f80-cebb-11eb-837f-5491107ad29a.jpg)

**Describe alternatives you've considered** 
**Additional context**

**Comment by gskinner** [comment]
I mean, this is a plugin developed in partnership with Adobe, so assisting people who steal their software isn't a priority.
