### ISSUE TITLE
Main component export

### ISSUE THREAD

**Issue by NinjaAtWork** [AdobeXD/xd-to-flutter-plugin#117]
Hi
While exporting linked component (for example button components from material kit to custom art-board ) there will be errors that raise cannot find Main Component
And after unlinking the copied component from their Main Kit file no more error raise but unlinking component is sometimes unwanted
Thanks

**Comment by gskinner** [comment]
Thanks for reporting this. My guess is that XD's API does not provide access to the linked component. I'll look into it though, and at worst we can hopefully provide a better error, add it to our test cases, and raise it with the XD team.

**Comment by NinjaAtWork** [comment]
👌
