### ISSUE TITLE
how to export the whole project with images and fonts?

### ISSUE THREAD

**Issue by FetFrumos** [AdobeXD/xd-to-flutter-plugin#119]
I'm new to XD to flutter. I like this tool, but I am confused by the lack of documentation and manuals. so I have a file xd. I want to create a flutter project from this file. I want to import all the images and all fonts. is it possible? any advice, I didn’t find how to do it.

**Comment by gskinner** [comment]
Have you looked at the README?
https://github.com/AdobeXD/xd-to-flutter-plugin/blob/master/README.md

Feel free to reopen this if you feel like it doesn't cover specific topics well enough.
