### ISSUE TITLE
'Image Export Name' cleared when I'm wrinting 

### ISSUE THREAD

**Issue by Islam-alshiki** [AdobeXD/xd-to-flutter-plugin#122]
## Bug Description
The text i'v write in Image Export Name is removed.

## To Reproduce
Select the image and click on plugin tab to set name, when I write some thing in filed It's cleared.

## Versions:

 - OS: Win 10
 - XD: 42.022.11
 - plugin: 2.0.0
 - Flutter: 2.2.3

**Comment by gskinner** [comment]
This seems to be working to me:

![image](https://user-images.githubusercontent.com/157128/141834289-11bd656a-4fd0-44c7-af73-659701e012ee.png)

Could you provide more information and reopen this issue? Are other text fields in the plugin working? Is this intermittent or consistent? Is it clearing as you type, or when you exit the field?
