### ISSUE TITLE
adobe_xd version isn't compatible with flutter svg package version

### ISSUE THREAD

**Issue by ItsYasser** [AdobeXD/xd-to-flutter-plugin#124]
## Bug Description

When you try to use this package now, it requires the flutter_svg ^0.21.0+1 but the flutter svg is updated to 0.21
many packages depend on flutter svg so if you try to downgrade the flutter svg version other packages will throw an error like for example the device preview package
### Example in the existence of many packages ( here: adobe xd , flutter svg , device preview ) 
```
adobe_xd >=2.0.0 depends on flutter_svg ^0.21.0+1 and app_test depends on flutter_svg ^0.22.0, adobe_xd >=2.0.0 is forbidden.
So, because app_test depends on adobe_xd ^2.0.0+1, version solving failed.
pub get failed (1; So, because app_test depends on adobe_xd ^2.0.0+1, version solving failed.)
exit code 1
```
## To Reproduce
upgrade the package to a newer version that is compatible with the newest version of flutter svg package

## Versions:

 - XD: 44.0.12.7
 - plugin: 3.0.0
 - Flutter: 2.5.1

**Comment by gskinner** [comment]
Apologies, we've been working on defining the next sprint. I was hoping that would happen quickly and we could just tackle this there, but it has not.

I'll try to take a look at this today, and hopefully push out a fix ASAP.

**Comment by gskinner** [comment]
I'd actually be interested in some community feedback here. Best practices suggest that we use caret syntax to avoid issues with breaking "major version" changes, but flutter_svg is still <1.0, and releases a lot of fairly minor changes as major versions (per the semantic system for <1.0).

It seems like it might be worth switching to:
`>=0.21.0`

This would risk incompatibilities with future versions, but given our limited exposure to the API (iirc only `SvgPicture.string`), that may be vastly preferable to drawing an arbitrary line in the sand for future compatibility and having the package break every release.

We could be a little more cautious and go with something like:
`>=0.21.0 <2.0.0`

Making the assumption that 1.0 is likely to be a direct descendant of <1.0, but that 2.0 is more likely to introduce breaking API changes.

Thoughts? @ItsYasser @FetFrumos

**Comment by gskinner** [comment]
In the interim, I believe the best practice for this would be to use a dependency override for your project:
https://dart.dev/tools/pub/dependencies#dependency-overrides

So you could force your project to use `0.2.3` for example, which should be compatible with the current version of adobe_xd. I'll test this soon to ensure.

**Comment by gskinner** [comment]
I've been giving this more thought, and I'm not convinced its in anyone's best interest to misrepresent our dependencies. Per the above, Flutter provides a mechanism to "properly" work around this issue.

I'll definitely test and update the supported version range in the upcoming release, and I'll also look at adding some documentation on this to the README.

Again, I'd welcome any additional thoughts on this.

**Comment by gskinner** [comment]
Just a quick update — Adobe should be pushing a v2.0.1 update to adobe_xd soon that will update the flutter_svg dependency to `^1.0.3`. Now that flutter_svg is on major versions, it _should_ reduce the frequency of future updates causing this issue. I'll close this off once it's live.

**Comment by gskinner** [comment]
FYI - v2.0.1 of adobe_xd is now live on pubdev.

**Comment by ItsYasser** [comment]
Awsome, nice work !

**Comment by gskinner** [comment]
Ha. Thanks! If only all issues could be resolved by changing 3 characters. :)
