### ISSUE TITLE
Error regarding adobe_xd ^3.0.0 in Visual Studio Code

### ISSUE THREAD

**Issue by catguy78** [AdobeXD/xd-to-flutter-plugin#125]
Seeing the following error when running in debugging mode in Visual Studio Code.

"Running "flutter pub get" in xd_to_flutter...
Because xd_to_flutter depends on adobe_xd ^3.0.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because xd_to_flutter depends on adobe_xd ^3.0.0 which doesn't match any versions, version solving failed.)
Exited (1)"

This was working yesterday after some trial and error of setting up and configuring the environment SDK to work with what is output from the XD to Flutter plugin. I was prompted to update Flutter this morning then this error came about.

environment:
  sdk: ">=2.11.0 <3.0.0" 
  
  dependencies:
  flutter:
    sdk: flutter
  adobe_xd: ^3.0.0
  flutter_svg: ^0.21.0+1

**Comment by catguy78** [comment]
Reverted back to adobe_xd: ^2.0.0 and issue is resolved

**Comment by andreaselia** [comment]
Must be due to no 3.0.0 release being tagged on pub, see here:

https://pub.dev/packages/adobe_xd/versions

**Comment by gskinner** [comment]
@catguy78 — Just for my own sanity, can you let me know where the `adobe_xd: ^3.0.0` came from? I don't see it anywhere on my end, but we're in the home stretch to deploy / tag off a new version, and I just want to be sure it's not something I need to fix. Thanks!

**Comment by catguy78** [comment]
I'll do my best to summarize, as I'm starting to regain my sanity today.
When I initially set this up from the following link:
https://jansalvadorsebastian.medium.com/convert-your-adobe-xd-design-to-flutter-codes-f41afe37aa9f
I was running into issues with the exported widgets from the plugin having
constructors with the following below, which was causing problems with non
nullable types and removing it every time I exported was tedious, till I
sorted out how to fix that as well.I think somewhere in my trial and error
to iron out the problems I was having and to test out a solid workflow and
eliminate errors in the exported widgets in my IDE, I saw this:
https://github.com/AdobeXD/xd-to-flutter-plugin/releases/tag/v3.0.0 and
updated my pubspec.yaml file to ^3.0.0 and my errors went away, or so I
thought, till I did my update this morning. I did not see the list that was
sent over by Andreas Elia. Since reverting back and restarting my IDE,
things are working good now.

Still trying to figure out how to export widgets that have actual text
fields and background images but that's beyond the context of this error I
was having.

In closing, you're not losing it, I was getting frustrated and happened to
try something different and got a false positive.

MobileLogin({
Key key,
}) : super(key: key);

**Comment by gskinner** [comment]
Great. I really appreciate the explanation! Had me a touch worried seeing this pop up at the 11th hour before releasing v4.0. :)

As an aside, `adobe_xd` version `2.0.1` is now on pubdev. The only change to it though is bumping up the version of `flutter_svg` to reduce version conflicts.
