### ISSUE TITLE
Proper way to use Code Export

### ISSUE THREAD

**Issue by cyrsis** [AdobeXD/xd-to-flutter-plugin#14]
This is a icon in the navbar

The code looks fantastic

![image](https://user-images.githubusercontent.com/731087/81832712-682f6100-9571-11ea-8a12-7143b0b53c32.png)

So Should I make it as image just export?

Or We are going to SVG everything?

**Comment by gskinner** [comment]
To clarify: You have a vector icon in a component, and would like to have different icons in different instances of the component?

**Comment by cyrsis** [comment]
I work out for my case is make it into png and export,

The used way is to make it into icon fonts when flutter with SVG time were little bit off.

Since SVG is the way to go(Somehow some edges is missing in some assets)
Note: Personally Check with it

For this XD project, probably just go back to SVG, and we can embedd some special asset into its own widget to make it ioslated and testable
