### ISSUE TITLE
SingleChildScrollView inside of the SizedBox For Text?

### ISSUE THREAD

**Issue by cyrsis** [AdobeXD/xd-to-flutter-plugin#15]
The flutter show correct Container Size and fonts specs

I wrote a plugin way back 

https://github.com/cyrsis/flutterXd

Would use ''' '''  better than SingleChildScrollView inside of the SizedBox?

![image](https://user-images.githubusercontent.com/731087/81834489-9150f100-9573-11ea-8a27-fc98012cf0b8.png)

**Comment by gskinner** [comment]
Hi @cyrsis - It's great to get your feedback given your experience in this space!

Sounds like two issues here:
1. Remove the SingleChildScrollView and rely on Flutter to automatically scroll the text.
2. Use preformatted strings (`'''`) for line breaks instead of `\n`

Is that correct?

**Comment by cyrsis** [comment]
Yes, would be much nicer, because SingleChildScrollView in RichText is Rare.

Most likely is a Container with Text label

**Comment by gskinner** [comment]
Took a first swing at the scroll view issue: b54d26d93818868aeb04bca63e7195c279128313

It will now only wrap text in a scroll view if the text box in XD has some overflow.

**Comment by gskinner** [comment]
I don't think we'll switch to pre-formatted strings, simply because I don't anticipate a lot of huge blocks of text, and I'd favor readability of the code over readability of the text strings. Feedback is welcome though.
