### ISSUE TITLE
Need ShortKey to Export Single Widget

### ISSUE THREAD

**Issue by cyrsis** [AdobeXD/xd-to-flutter-plugin#16]
Asset Panel and Plugin Panel can not open at the same time.

![image](https://user-images.githubusercontent.com/731087/81836459-176e3700-9576-11ea-8cd5-ce9320481d33.png)

it is crazy tedious go back hit "UI Panel"

**Comment by gskinner** [comment]
This would be an easy thing to add. Does `cmd-shift-opt-f` sound like a reasonable shortcut?

**Comment by cyrsis** [comment]
Sure, since it is your work, so
may be 
cmd+ option +g sounds better

**Comment by gskinner** [comment]
Added two new keyboard shortcuts:
cmd-shift-opt-f: Export Selected Widget
cmd-opt-c: Copy Selected

In 51b587b6e62081c3bc27488f1c4df5359e07dd8a
