### ISSUE TITLE
Negative grid spacing causes errors in Flutter

### ISSUE THREAD

**Issue by giri-jeedigunta** [AdobeXD/xd-to-flutter-plugin#19]
I created a simple design with a grid layout on Adobe XD. When I exported with new plugin the app ran into errors. 

![image](https://user-images.githubusercontent.com/2689410/81900806-2dfaa980-95db-11ea-807e-c3d446953aaa.png)

![image](https://user-images.githubusercontent.com/2689410/81900988-79ad5300-95db-11ea-93eb-0d2fa3947e2f.png)

Here are the specific lines that are causing the error: 

`
mainAxisSpacing: -267,
crossAxisSpacing: -122,
`

**Full error Log:** 

`Launching lib/main.dart on iPhone 11 Pro in debug mode...
Xcode build done.                                           21.2s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building iPhoneXXS11Pro1(dirty):
flutter: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 302 pos 15:
flutter: 'mainAxisSpacing != null && mainAxisSpacing >= 0': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   iPhoneXXS11Pro1
[38;5;248mflutter:[39;49m
flutter:
flutter: When the exception was thrown, this was the stack:
[38;5;244mflutter: #2      new SliverGridDelegateWithFixedCrossAxisCount[39;49m
[38;5;244mflutter: #3      new GridView.count[39;49m
[38;5;248mflutter: #4      iPhoneXXS11Pro1.build[39;49m
[38;5;244mflutter: #5      StatelessElement.build[39;49m
[38;5;244mflutter: #6      ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #7      Element.rebuild[39;49m
[38;5;244mflutter: #8      ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #9      ComponentElement.mount[39;49m
flutter: ...     Normal element mounting (24 frames)
[38;5;244mflutter: #33     Element.inflateWidget[39;49m
[38;5;244mflutter: #34     MultiChildRenderObjectElement.mount[39;49m
flutter: ...     Normal element mounting (119 frames)
[38;5;244mflutter: #153    Element.inflateWidget[39;49m
[38;5;244mflutter: #154    MultiChildRenderObjectElement.mount[39;49m
flutter: ...     Normal element mounting (253 frames)
[38;5;244mflutter: #407    Element.inflateWidget[39;49m
[38;5;244mflutter: #408    Element.updateChild[39;49m
[38;5;244mflutter: #409    RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244mflutter: #410    RenderObjectToWidgetElement.mount[39;49m
[38;5;244mflutter: #411    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244mflutter: #412    BuildOwner.buildScope[39;49m
[38;5;244mflutter: #413    RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244mflutter: #414    WidgetsBinding.attachRootWidget[39;49m
[38;5;244mflutter: #415    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
flutter: (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
`

**Plugin generated code:** 
[iPhoneXXS11Pro1.dart.txt](https://github.com/AdobeXD/xd-to-flutter-plugin/files/4626491/iPhoneXXS11Pro1.dart.txt)

**Comment by gskinner** [comment]
Interesting. I don't think we even realized that XD supported negative grid spacing. I think supporting this in the output could get really hairy (at least without a fully custom grid implementation), but minimum we should add a warning for this and output it as 0.

**Comment by cyrsis** [comment]
I have this problem way back,

some people use Position Widget to solve it, end up everything is in  a Stack.

Some upside but lot more code for me

**Comment by gskinner** [comment]
Fixed in f74811608fe29964da099cd86846f6977665f34c
