### ISSUE TITLE
Question Why a lot of Transform.translate?

### ISSUE THREAD

**Issue by amreniouinnovent** [AdobeXD/xd-to-flutter-plugin#20]
It is really will be a great tool
I wonder why generated widgets have a lot of Transform.translate?
And is it will be changed in the future?

**Comment by ketankshukla** [comment]
I'm sure it's coming. For instance, a Button component with all its properties set and designed in XD and then exported directly into Flutter code. THIS would make it a proper designer.

**Comment by gskinner** [comment]
Please see: #13

Currently we only have arbitrary positioning information in XD to work from. Once layout support is added, it should let us create smarter outputs.

We also have some ideas around future features that would let you hint to the exporter what an element is intended to become (ex. a button).
