### ISSUE TITLE
Export single Artboard doesn't update component dart code

### ISSUE THREAD

**Issue by opsopus** [AdobeXD/xd-to-flutter-plugin#25]
When artboard link some component, export single artboard with Widget hasn't component dart file.

**Comment by gskinner** [comment]
To clarify: If you use Export Widget to export a selected Artboard, and that Artboard contains a Component, you would like it to also export the Component widget? We had a few internal discussions about this and made the decision that Export Widget would always just export / update the selected element, so we weren't overwriting files you didn't expect.

I'm open to changing this though, and would welcome discussion about it.
