### ISSUE TITLE
Change default widget name prefix to XD

### ISSUE THREAD

**Issue by hemish11** [AdobeXD/xd-to-flutter-plugin#33]
Though this is not a big thing or a thing that may break anything but the default for _WIDGET NAME PREFIX_ is XD_ and flutter has camel case for naming any variable or class in which '_' are not allowed. So it would be good if '_' is not present in any Name. Thus would not break anything but is good as flutter applications are based on Camel Case.
Here is the screenshot and the text is highlighted:
<img width="192" alt="Screenshot 2020-05-17 at 3 17 16 PM" src="https://user-images.githubusercontent.com/46677360/82141171-b08c9e80-9851-11ea-9b5f-e5e8ffb8878b.png">

**Comment by gskinner** [comment]
We debated this internally before deciding on `XD_` because it was so prominent, but I'm rethinking it now.

If we were to make this change, we'd want to do it ASAP (ie. in 0.1.2), so it doesn't break too many people's dependencies on the default naming.

Feedback is welcome.

**Comment by hemish11** [comment]
is it good to set it to Widget or Screen and as suffix not as prefix as many developer use those in their apps or set My as prefix as it is also a common prefix name.

**Comment by gskinner** [comment]
Fixed in 646193938c18b2975f4c69b83ea8e665b58d792f
