### ISSUE TITLE
Reserved words in parameter names cause issues

### ISSUE THREAD

**Issue by hemish11** [AdobeXD/xd-to-flutter-plugin#34]
In my project Artboard 1 and Artboard 2 are both similar. They both have 'Test' Text in centre but in Artboard 1, the parameters of Text namely 'TEXT PARAMETER' and 'COLOR PARAMETER' are typed to null. When I click on export all widgets it does not give any error message but only exports Artboard 2 and does not export Artboard 1 in which both parameters are set to null. This also happens when any one of the parameter is set to null. Though null cannot be set as parameter but plugin also does not show any error message. It should show error message namely 'Null cannot be set as parameter in TEXT PARAMETER or COLOR PARAMETER'.
Maybe my xd file could help so here is my xd file in zip in which this issue occurs:
[XD to Flutter 2.zip](https://github.com/AdobeXD/xd-to-flutter-plugin/files/4640020/XD.to.Flutter.2.zip)

**Comment by gskinner** [comment]
Ah, I see. Yes, I expect any reserved word will cause issues as a param name. The fix would be to assemble a list of reserved words in Dart, and then either throwing an error, or modifying the name - likely the latter to avoid a bunch of UI.

**Comment by gskinner** [comment]
This would almost certainly be true for widget names as well.

**Comment by hemish11** [comment]
Up till now I was able to see this error only with `null`. For this, I had checked `undefined` and many other similar one.

**Comment by gskinner** [comment]
Fixed in 03b5227c07b32c160ddd611d774cdeebc10c496b
