### ISSUE TITLE
Same param name for different value types causes errors

### ISSUE THREAD

**Issue by hemish11** [AdobeXD/xd-to-flutter-plugin#35]
In my project Artboard 1, Artboard 2 and Artboard 3 are all similar. They all have 'Test' Text in centre.
In Artboard 1, the parameters of Text namely 'TEXT PARAMETER' and 'COLOR PARAMETER' are set to 'Text' and 'Color' which both are name of widget in flutter and both are names for class and not for variable as Class should have first letter upper case and variable should not have.
In Artboard 2, the parameters of Text namely 'TEXT PARAMETER' and 'COLOR PARAMETER' are both set to test as two variables should not have same name, plugin creates one variable bit has reference to two place and at one place, Color is the required variable type but on other, String is required variable type. As variable with different type is assigned to other one, it makes an error. in flutter code.
Whereas in Artboard 3, the parameters of Text namely 'TEXT PARAMETER' and 'COLOR PARAMETER' are set to text and color which both are proper name for variable and hence flutter does not show any error.
So to solve this, plugin should check that both parameters don't have upper case letter and both should not be same. And if they have, then plugin may show an error according to the condition which was false.

Here is my xd file in zip in which this issue occurs:
[XD to Flutter 3.zip](https://github.com/AdobeXD/xd-to-flutter-plugin/files/4640040/XD.to.Flutter.3.zip)

**Comment by gskinner** [comment]
We don't plan to enforce naming conventions (Ex. capitalization). For the issue of identical param names, we actually do generate a warning.

![image](https://user-images.githubusercontent.com/157128/82160770-e1ba9e00-9854-11ea-8450-e386ee0b3141.png)

There are two scenarios, which we currently don't differentiate between:
1. Two identical names for params of the same type. It can actually be handy to ignore the warning for this in some cases, like if you want the same color used on two text elements.
2. Identical param names for params of different types. This can cause errors.

I wonder if we should remove the warning for the first scenario, and upgrade the second scenario to an error.

Feedback welcome.

**Comment by hemish11** [comment]
Here is the screenshot of the type of error I was thinking to show.
<img width="550" alt="Screenshot 2020-05-18 at 10 02 37 PM" src="https://user-images.githubusercontent.com/46677360/82237928-0e091400-9954-11ea-85d5-980d8e94621e.png">
It would be nicer to show error like this when this happens. And Error should be shown for both scenario. To check first scenario is pretty simple as we need to check for both their equality. For second scenario We have to check whether the first character is uppercase or not as all the class or widget name have first letter to be upper case. We have to also check for first character not to be number as variables with first character to be number are not considered to be proper variable in flutter.
For error we need to change title as Error and content accordingly as well as to change the Text of  `Continue` button to `Ok`.

Thanks in advance

**Comment by gskinner** [comment]
I just pushed c6b6ba4e1f1612de9deedc31dfe3e334e1e1be79, which (among a bunch of other things) improves on the handling of duplicate member names. It now warns for two members of identical type, and errors for different types. It also provides much better messages (see screenshot).

![image](https://user-images.githubusercontent.com/157128/117217510-b959e580-adbe-11eb-8889-7058e0e030e1.png)

**Comment by gskinner** [comment]
As a note, I added an error icon to the results area to call better attention to problems.

![image](https://user-images.githubusercontent.com/157128/117367006-c9d19500-ae7e-11eb-9484-e0775a226b9b.png)
