### ISSUE TITLE
404 link on example page

### ISSUE THREAD

**Issue by MarcelEdward2** [AdobeXD/xd-to-flutter-plugin#37]
On the example page https://pub.dev/packages/adobe_xd#-example-tab-
the link points to https://github.com/AdobeXD/xd-to-flutter-plugin/blob/master/example/lib/main.dart

**Comment by gskinner** [comment]
Good catch. This looks like an issue with pubdev. It seems like it is expecting the dart package to live at the root of the repo, and is auto-generating the link based on that.

I confirmed previously with the Flutter team that having the dart package in its own repo is not a requirement or even a best practice, so I'm not sure how we fix this.

If anyone has any thoughts, I'd love to hear them.

**Comment by cheseren** [comment]
i got same error

**Comment by gskinner** [comment]
This should be fixed now via 3eabfae86e79fe1ef45e7234c933f74a2384c33c
