### ISSUE TITLE
Unable to format the exported source code

### ISSUE THREAD

**Issue by 1037975742** [AdobeXD/xd-to-flutter-plugin#41]
1 Error:
[bicker_publish_page…] Unable to format the exported source code.

2 Warnings:
Could not find assets entry in pubspec.yaml for: assets/images/.
Could not find fonts entry in pubspec.yaml for: PingFang SC.

**Comment by gskinner** [comment]
Are you able to share the `.xd` file that you're seeing this issue with? Ideally with everything removed except what's causing the error.

**Comment by Fermentis** [comment]
I had the same issue and found it was textbox related. I had to copy the on screen text, paste it into a text editor in order to strip it of any formatting, then copy it back into the textbox. It would then export just fine.

**Comment by gskinner** [comment]
@Fermentis - it sounds like you may have found another character that needs to be encoded. Any chance you could share the file stripped down to just the text field that's causing the problem?

**Comment by gskinner** [comment]
Closing since this can't be fixed without more information.
