### ISSUE TITLE
We need Figma to Flutter Plugin too

### ISSUE THREAD

**Issue by Blaqmac** [AdobeXD/xd-to-flutter-plugin#42]
The tech ecosystem is supposed to be a case of inclusion where everyone is welcome to the table. I don't know why we designers using Figma as our major design tool should be deprived of the opportunity to add this plugin to our workflow. Please I and many other Figma users would be glad if our cry is heard and we also get included to start using this Flutter plugin to make design handoff easy collaborating with our team members using Dart/Flutter. #

**Comment by shenzhen-xi** [comment]
ask Figma maybe?
