### ISSUE TITLE
Everything is aligned to the left

### ISSUE THREAD

**Issue by uefigod** [AdobeXD/xd-to-flutter-plugin#43]
![image](https://user-images.githubusercontent.com/28818229/82751825-9ade2280-9dd7-11ea-9dbd-2a13cb9eab44.png)

idk what I'm doing wrong, the highlighted portion is the stack widget from dart dev tools

heres what it looks like in XD
![image](https://user-images.githubusercontent.com/28818229/82751887-f3152480-9dd7-11ea-8765-1be965679cfa.png)

**Comment by gskinner** [comment]
Currently, everything is exported using static positioning/sizing. What you're seeing is just that your emulator's screen is larger than your artboard, so there's extra space around it.

Adobe just released layout APIs for XD, and we're planning to release a plugin update (likely v0.2.0) that will leverage those APIs to provide responsive layout.

**Comment by gskinner** [comment]
See: https://github.com/AdobeXD/xd-to-flutter-plugin/issues/13

**Comment by uefigod** [comment]
Hey that sounds amazing! :D all the best to you guys
