### ISSUE TITLE
All layers which were aligned at center in XD are not aligned center in Flutter

### ISSUE THREAD

**Issue by betterplanet** [AdobeXD/xd-to-flutter-plugin#45]
When I export all widgets to Flutter. 
I see the layers which were aligned at center in XD are not at center in emulator.

Is there a fix coming for this? 
Also, there are errors while loading images but I am trying to investigate that. 
I will raise a separate issue for that

The center alignment is much needed to save my effort as I want to keep all design work in XD. 

![image](https://user-images.githubusercontent.com/65831290/82906489-f39dee80-9f82-11ea-894b-34ca0718a265.png)
![image](https://user-images.githubusercontent.com/65831290/82906538-0adcdc00-9f83-11ea-9687-5fc8c2c315d9.png)

**Comment by gskinner** [comment]
Please see #43
