### ISSUE TITLE
Clarify need for latest version of XD installed

### ISSUE THREAD

**Issue by alyxb** [AdobeXD/xd-to-flutter-plugin#47]
**Issue:**
- In the "Installation & Setup" section of the [README](https://github.com/AdobeXD/xd-to-flutter-plugin#installation--setup), it is not clear that the user must have XD updated to the latest version.
- If XD isn't updated to the latest version, then the plugin will not display when one searches for "Flutter" in the Discover Plugins modal.

**Proposed change:**
- In README.md, add this below line 24:

`Make sure you've updated to the latest version of XD. Otherwise, the plugin might not appear in the Discover Plugins modal.`

**Comment by gskinner** [comment]
I had assumed it would show up, but display a warning to update. Thanks for bringing this to my attention.

**Comment by gskinner** [comment]
I've provided feedback to Adobe, will update the README, and may look at whether we can do the version detection on the plugin side for the next release.

**Comment by gskinner** [comment]
Added a note to the README in d907e4261dcf300d4959422fd44312ef963ce756

Going to leave this open to see if we can find a better solution in v0.2.0

**Comment by gskinner** [comment]
Added run time version checking to the plugin in 81d6c03ed24652d4a36045beb02a96feea7b31ad

This should let us reduce the minimum version in the marketplace, and instead warn users in the panel.
