### ISSUE TITLE
Image export name gets dropped in some scenarios.

### ISSUE THREAD

**Issue by gskinner** [AdobeXD/xd-to-flutter-plugin#48]
The image export name property will sometime revert to empty. I believe this is probably related to our image matching logic, where if an image was dragged in from the local system, it uses it's file path (indirectly, via a hack) to try to match up duplicate images. If that file path changed for any reason, it would break the association and revert the name.

I'd hate to get rid of that functionality, since it makes working with images significantly better, but it's certainly not ideal if that data gets wiped unexpectedly because an image file moves or the xd file is shared to another system.

Still hoping for an `ImageFill.imageHash` or `.imageId` API in XD, as that would solve this and many other problems.

I'm not 100% sure of the cause yet, it requires some investigation.

**Comment by gskinner** [comment]
A bit more digging suggests that XD changed its `ImageFill.toString()` return value to now include dimensions `ImageFill(filename.jpg 750x497)`, which broke existing associations.

**Comment by gskinner** [comment]
At minimum, we should probably update the example file so that it uses copy pasted images, so they don't have the same problem. Maybe there's a way to update the matching system to a more hybrid approach, so that it can still be used to find duplicates, but isn't used as the ID for associating data.

**Comment by gskinner** [comment]
66e7d5db1b4a3a2cbef4784879da143e184aaae2 makes it so that the image name is stored on both the instance and in the hash. This doesn't solve all scenarios, but should prevent issues with the example. This really needs a solution on the XD side.

**Comment by peterflynn** [comment]
@gskinner In XD29 (where `toString()` changed), we added a [new `assetId` property](https://adobexdplatform.com/plugin-docs/reference/ImageFill.html#ImageFill-assetId) to ImageFill so you can tell when two fills use the same image. It was designed to with this exact use case in mind, so hopefully it will help here.

**Comment by gskinner** [comment]
Ah, that's fantastic @peterflynn! I will implement that for v0.2.0

**Comment by gskinner** [comment]
Added in 44e2352f646c14bb3fdae6e5e47dea8adfa57030
