### ISSUE TITLE
Discover Plugins could not find in Adobe XD

### ISSUE THREAD

**Issue by liudonghua123** [AdobeXD/xd-to-flutter-plugin#49]
In the `Installation & Setup` step.

> In the Adobe XD menubar, go to Plugins > Discover Plugins, then search for and install the "Flutter" plugin. It will now show up in your plugins sidebar in the bottom left of XD.

I installed the latest xd, but could not found `Discover Plugins`, the version of installed is `29.1.32.8`.

The following are some related snapshots.

![image](https://user-images.githubusercontent.com/2276718/83093938-09222e00-a0d3-11ea-89f4-0b8576baf7f2.png)

![image](https://user-images.githubusercontent.com/2276718/83093955-13442c80-a0d3-11ea-81bf-d13f83a9dae7.png)

**Comment by liudonghua123** [comment]
Could you provide a `xdx` file download like https://github.com/thize/xd-to-flutter/releases for easier installation.

**Comment by gskinner** [comment]
What version of XD are you using? If it's <28, then the store won't show the plugin unfortunately. See #47

**Comment by liudonghua123** [comment]
@gskinner Hi, I am using `29.1.32.8`.

**Comment by yeganehaym** [comment]
same too
i even went to figma and changed my app but i dont know how this app working and i need to discover abilities again here and dont have time
