### ISSUE TITLE
Cannot export shape since version v0.1.3

### ISSUE THREAD

**Issue by ltonn02** [AdobeXD/xd-to-flutter-plugin#53]
**Describe the Bug**
Since version v0.1.3 I cannot export SELECTION:Shape objects from my xd project to flutter.
When I click the button to "copy selected" nothing happens.

**To Reproduce**
- Import SVG object into project
  (in my case I get these from the "Icons 4 Design" plugin)
- select shape
- click "copy selected"

**Screenshots and/or XD File**
[bug.xd.zip](https://github.com/AdobeXD/xd-to-flutter-plugin/files/4783073/bug.xd.zip)

**Console Output**
Plugin Error: Plugin Promise was rejected with: Path.toString called.
    at convertPluginErrorToString (plugins/PluginErrorUtil.js:1:198)
    at safeGetStackTrace (plugins/PluginErrorUtil.js:1:339)
    at internalFormatPluginError (plugins/PluginErrorUtil.js:1:1073)
    at internalReportPluginError (plugins/PluginErrorUtil.js:1:1171)
    at Object.reportPluginError (plugins/PluginErrorUtil.js:1:1603)
    at plugins/ScenegraphGuard.js:1:5659

**OS & XD Version:**
 - OS: 10.15.5
 - XD: 29.3.32.3
 - XD to Flutter: v0.1.3

**Comment by gskinner** [comment]
I can reproduce this, and will look into a fix. Thanks for the report!

**Comment by gskinner** [comment]
Quick note: this happens for both copy selected & export (one) widget. It does not happen with Export All.

**Comment by gskinner** [comment]
Fixed locally. Will be in v0.2.0
