### ISSUE TITLE
Color Assets not exported

### ISSUE THREAD

**Issue by vennussoftwares** [AdobeXD/xd-to-flutter-plugin#54]
I've been working on a UI recently in AdobeXD and when I finished everything up and was ready to export to flutter, one annoying thing happened when I was testing. I had the unpleasant surprise to discover that my background color was missing! I figured out that I didn't select export color assets. Unfortunately, this did not solve my problem.

**Comment by gskinner** [comment]
What version of the plugin & XD are you using? Can you provide an XD file that shows the issue?

**Comment by gskinner** [comment]
Closing due to lack of additional info. Please feel free to reopen with details.

**Comment by RaviInexture** [comment]
I am facing the same issue with given versions.

**XD Version**: 30.1.12.4 (Starter), Creative Cloud Sync 4.3.48.36
**XD to Flutter Plugin Version**: 0.1.3

**Comment by gskinner** [comment]
I'm guessing you have a gradient background? If so, I just added a warning in 6bf115a784cbc26c70a8b577c7e2e0b4bbb469cd, and made it so that it will use the first color in the gradient as the artboard background.

**Comment by RaviInexture** [comment]
> I'm guessing you have a gradient background? If so, I just added a warning in [6bf115a](https://github.com/AdobeXD/xd-to-flutter-plugin/commit/6bf115a784cbc26c70a8b577c7e2e0b4bbb469cd), and made it so that it will use the first color in the gradient as the artboard background.

No, I didn't use any gradient background.

**Comment by gskinner** [comment]
Hmm. In that case I have no clue what could be happening. We're just reading the value direct from the API. Without an XD file demonstrating this issue, I can't think of anything else to test. If you're able to provide one, I appreciate it.
