### ISSUE TITLE
Hi, it would be great and really help all flutter developers if they can convert the components from xd to widgets like BUTTON , TEXTFIELD, LISTVIEW, ANIMATIONS like bounce effect etc..

### ISSUE THREAD

**Issue by mohsinhundekar** [AdobeXD/xd-to-flutter-plugin#56]
_We love to hear your ideas, but we need your help. Please take a few minutes to fill out the information below, and provide a concise, descriptive title._

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shashank132** [comment]
yes , it would be better if "xd to flutter " plugin can convert the textfield ( if user click on the textfield he can able to write ), button , screen redirection after 5 sec or in specific time duration .
![cid](https://user-images.githubusercontent.com/38376831/86319436-2c03ad00-bc52-11ea-9470-a0f272ce17ff.png)
