### ISSUE TITLE
Page Transition Flutter Error

### ISSUE THREAD

**Issue by MACHINE666** [AdobeXD/xd-to-flutter-plugin#64]
_We are committed to trying to solve issues, but we need your help. Please take a few minutes to fill out the information below, and provide a concise, descriptive title._

**Describe the Bug**
Requesting page transition on Adobe XD and importing to Flutter does not work.

 Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xffa52121),
      body: Stack(
        children: <Widget>[
      Transform.translate(
      offset: Offset(69.0, 436.0),
      child: PageLink(
        links: [
          PageLinkInfo(
            transition: LinkTransition.Fade,
            ease: Curves.easeOut,
            duration: 0.3,
            pageBuilder: () => iPhone678Plus1(),
          ),
        ],

PageLink, I tried searching for the term, couldn't find it in the flutter documentation

<img width="823" alt="image" src="https://user-images.githubusercontent.com/67407156/87443349-6da73700-c606-11ea-9eb2-388555025db3.png">

**To Reproduce**
Specific steps to reproduce the behavior.

**Screenshots and/or XD File**
If possible, add a link to an XD file that demonstrates the problem in the simplest way possible (ie. isolate just the artboard and layer that is causing the problem). If applicable, add screenshots to help explain your problem.

**Console Output**
{
	"resource": "/Users/amroel/Developer/AndroidStudioProjects/flutteradobe/lib/iPhone678Plus1.dart",
	"owner": "dart",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/tools/diagnostic-messages#undefined_method",
			"path": "/tools/diagnostic-messages",
			"scheme": "https",
			"authority": "dart.dev",
			"fragment": "undefined_method"
		}
	},
	"severity": 8,
	"message": "The method 'PageLink' isn't defined for the type 'iPhone678Plus1'.\nTry correcting the name to the name of an existing method, or defining a method named 'PageLink'.",
	"source": "dart",
	"startLineNumber": 17,
	"startColumn": 20,
	"endLineNumber": 17,
	"endColumn": 28,
	"tags": []
}
**OS & XD Version:**
 - OS:  MacOS 10.15.3]
 - XD: 30.2.12.3

**Other Information:**
Any other information you think might be useful, or hunches you have on what's going wrong.

**Comment by gskinner** [comment]
Please refer to the README file, under Flutter Dependencies. You should also get a warning informing you about the missing adobe_xd package. Please feel free to reopen if this doesn't address your issue.
