### ISSUE TITLE
Radius.elliptical has 9999.9 for x and y

### ISSUE THREAD

**Issue by PearlByte** [AdobeXD/xd-to-flutter-plugin#67]
**Describe the Bug**
In every artboard or file, after my update to v1.0.0 I see that the Radius.elliptical values are incorrect as follows:
old version:
decoration: BoxDecoration(borderRadius: BorderRadius.all(Radius.elliptical(11.0, 11.0))),

new version:
decoration: BoxDecoration(borderRadius: BorderRadius.all(Radius.elliptical(9999.0, 9999.0))),

**To Reproduce**
Create an elliptical object in an artboard and export the artboard as a widget.

**OS & XD Version:**
 - OS: MacOS 10.15.5
 - XD: 31.1.12.13

**Other Information:**
I currently do not see a problem as the elliptical looks correct in my flutter app, but I feel this needs to be correct and could cause issues in the future.

Regards,
Ziad
PearlByte

**Comment by gskinner** [comment]
The reasoning for this is to support responsive resize. Setting the radius to 9999 allows "ellipses" created in this way to resize and retain their shape. We did some testing, and didn't see any problems from it, but please feel free to reopen if you have further concerns.
