### ISSUE TITLE
                        Pinned.fromSize(

### ISSUE THREAD

**Issue by EngMotassem** [AdobeXD/xd-to-flutter-plugin#68]
generated code 

import 'package:adobe_xd/pinned.dart';

**Comment by gskinner** [comment]
I'm not sure what this is asking or reporting. Closing, but feel free to reopen with more info. Possibly this is a duplicate of #74 ?

**Comment by iinfinitii** [comment]
Add dependency adobe_xd: ^1.1.0+1 into pubspec.yaml and run flutter pub get
