### ISSUE TITLE
Failure to Export Screens: Plugin ReferenceError: xdNode is not defined

### ISSUE THREAD

**Issue by hamada147** [AdobeXD/xd-to-flutter-plugin#71]
**Describe the Bug**
I downloaded the following UIKit for testing the plugin [Fresh Food UI Kit by Daniel White](https://adobe.ly/xdfreshfooduikit). I installed the XD to Flutter plugin from the Adobe XD itself. I've set up the path to the flutter project root folder. Clicked on export all widget buttons. Only two screens appear in the Flutter project and nothing else is being exported. I have to go and export each screen on its own. Then more than one screen doesn't generate the dart code (ex: Onboarding 1 (light)).

**To Reproduce**
1. Downloaded the following UIKit [Fresh Food UI Kit by Daniel White](https://adobe.ly/xdfreshfooduikit).
2. Install the latest version of XD to Flutter plugin from the Adobe XD (1.0.0 July 27, 2020).
3. Create a new flutter project using the following command `flutter create myapp`.
4. Set the XD to Flutter plugin flutter path to the newly created flutter project.
5. Open the plugin inside the Adobe XD.
6. Click on "Export All Widgets" button => only export two-screen (SplashScreendark, StoreMenuDragdark).
7. No error is being shown to the user that something went wrong.

**Screenshots and/or XD File**
The Adobe XD file can be downloaded from the following link [Fresh Food UI Kit by Daniel White](https://adobe.ly/xdfreshfooduikit).

**Console Output**
```
Plugin ReferenceError: xdNode is not defined
    at l (<settings>/plugins/6eaf77ea/main.js:1:89631)
    at a._serialize (<settings>/plugins/6eaf77ea/main.js:1:89240)
    at a.serialize (<settings>/plugins/6eaf77ea/main.js:1:22069)
    at e.Component._decorate (<settings>/plugins/6eaf77ea/main.js:1:11998)
    at e.Component._serialize (<settings>/plugins/6eaf77ea/main.js:1:77918)
    at e.Component.serialize (<settings>/plugins/6eaf77ea/main.js:1:38054)
    at <settings>/plugins/6eaf77ea/main.js:1:12136
    at Array.forEach (<anonymous>)
    at s._getChildList (<settings>/plugins/6eaf77ea/main.js:1:12113)
    at s._getChildStack (<settings>/plugins/6eaf77ea/main.js:1:12334)
```

**OS & XD Version:**
 - OS: MacOS 10.15.5 (19F101)
 - XD: 32.2.12.4 (Starter)

**Other Information:**
Any other information you think might be useful, or hunches you have on what's going wrong => No idea, to be honest.

**Comment by gskinner** [comment]
The fix for #72 (300a6998bc6c6622862788c96578ff3f0961b23d) appears to have fixed this as well (I was able to export the full UIKit: 153 widgets, and 25 logged errors). I'm closing this issue in favor of #72.
