### ISSUE TITLE
adobe_xd/pinned.dart is missing in adobe_xd: 0.1.4 package for MacOS

### ISSUE THREAD

**Issue by simemap** [AdobeXD/xd-to-flutter-plugin#74]
**Describe the Bug**
I am using Flutter with VSCODE in a **MacOS**. Just imported a file from AdobeXD and I am getting an error when `import 'package:adobe_xd/pinned.dart'; `. 
This is the error:
```
Target of URI doesn't exist: 'package:adobe_xd/pinned.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.darturi_does_not_exist
```
In fact this lib doesn't exists in the `flutter/.pub-cache/hosted/pub.dartlang.org/adobe_xd-0.1.4/lib`. This is what I have in the lib folder:
```
total 48
drwxr-xr-x   7 ialves  27132083   224 29 Aug 11:31 .
drwx------  10 ialves  27132083   320 29 Aug 11:31 ..
-rw-r--r--   1 ialves  27132083   494 13 May 16:15 adobe_xd.dart
-rw-r--r--   1 ialves  27132083  1884 13 May 16:57 blend_mask.dart
-rw-r--r--   1 ialves  27132083  1865 13 May 17:20 gradient_xd_transform.dart
-rw-r--r--   1 ialves  27132083  5685 13 May 17:20 page_link.dart
-rw-r--r--   1 ialves  27132083  1022 13 May 16:15 specific_rect_clip.dart 
```
Seems to be missing the `package:adobe_xd/pinned.dart` lib. Maybe this is origin of the issue.
The `flutter clean` and `flutter packages get` didn't fix the issue.

**To Reproduce**
Install Flutter for MAC and adobe_xd and import any file from adobe_xd that is using the CLASS `Pinned.`. It will fail to import `package:adobe_xd/pinned.dart`.

**Screenshots and/or XD File**
<img width="673" alt="Screen Shot 2020-08-29 at 13 00 35" src="https://user-images.githubusercontent.com/53879786/91642234-b6b91c00-e9f7-11ea-9d78-79265747d3b6.png">
See more details in this [Stackoverflow post](https://stackoverflow.com/questions/63649488/flutter-import-packageadobe-xd-pinned-dart-target-of-uri-doesnt-exist).

**Console Output**

There is no `adobe_xd/pinned.dart` lib in the adobe_xd-0.1.4 package. 
```
~/Documents/vhosts/flutter/.pub-cache/hosted/pub.dartlang.org/adobe_xd-0.1.4/lib(stable)$ ll
total 48
drwxr-xr-x   7 ialves  27132083   224 29 Aug 11:31 .
drwx------  10 ialves  27132083   320 29 Aug 11:31 ..
-rw-r--r--   1 ialves  27132083   494 13 May 16:15 adobe_xd.dart
-rw-r--r--   1 ialves  27132083  1884 13 May 16:57 blend_mask.dart
-rw-r--r--   1 ialves  27132083  1865 13 May 17:20 gradient_xd_transform.dart
-rw-r--r--   1 ialves  27132083  5685 13 May 17:20 page_link.dart
-rw-r--r--   1 ialves  27132083  1022 13 May 16:15 specific_rect_clip.dart
```
**OS & XD Version:**
 - OS: MAC 10.15.5
 - XD: 0.1.4

**Comment by PearlByte** [comment]
Did you figure this out? It sounds like a mismatch between your plugin and the version of the package you are specifying in the pubspec.yaml file. Use the latest package: 1.0.0 or greater.

**Comment by gskinner** [comment]
@PearlByte is correct. It sounds like you are using an older version of the adobe_xd package. This raises an interesting point though: it would be nice if we detected these version mismatches. I've added #80 to track this.

**Comment by marshi96** [comment]
change your sdk version to 2.10.4

```
environment:
  sdk: ">=2.10.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  adobe_xd: ^1.0.0+1
  flutter_launcher_icons: ^0.8.1
```
