### ISSUE TITLE
is this plugin still being developed?

### ISSUE THREAD

**Issue by bedirhanwerk** [AdobeXD/xd-to-flutter-plugin#77]
Hello,

I am curious if this plugin is still in development as I see no changes recently?

Thanks in advance.

**Comment by brunoribei-ro** [comment]
I dont think so! In 6 months Flutter has changed a lot and the plugin was left behind.

**Comment by PearlByte** [comment]
I don't know... I still can use it with the latest version of Flutter. I
feel it is backed up by Adobe and Google and should get an update soon.

-Zee
PearlByte, Inc.

**Comment by gskinner** [comment]
Thanks for your interest! There was an unexpectedly long pause as the i's were dotted and t's crossed, but there is now a plan to move forward. I've posted some details here: #79 , and am happy to answer any questions.
