### ISSUE TITLE
Adobe XD to Flutter question. Flutter doesn't show the correct screen on AVD?

### ISSUE THREAD

**Issue by gsb216200** [AdobeXD/xd-to-flutter-plugin#82]
So I am new to this. I can design and now I am trying to learn code with my XD designs. After figuring out the dependency issues. I launched my app on my AVD and on my phone it starts with a random screen from my app not even the login screen? I am looking through my A dart and B dart and I am lost how to get this thing to start at the correct screen that I ordered in prototype in XD. Can someone please help? The interactions don't work properly either? Do I have to upload each screen separately to make this work? 
![1](https://user-images.githubusercontent.com/17156688/101293556-7a0c7600-37d9-11eb-8bcc-36b5cd87fddc.PNG)
![2](https://user-images.githubusercontent.com/17156688/101293572-7bd63980-37d9-11eb-8058-f10a817a0311.PNG)

**Comment by gskinner** [comment]
It looks to me like you are either copying generated dart code into your main file, or are just using one of the generated files as main.

I'm hoping we will have a "getting started" video soon which will demonstrate project setup, but for now, please make sure you look through the README fully, and use the sample application `/adobe_xd/example` to see how the views from XD can be consumed in an app.

**Comment by gsb216200** [comment]
That's how to code shows up after I export all widgets? I'll look into that and see how it can be fixed.

**Comment by gsb216200** [comment]
I got it to work with a fresh project on flutter. But how come the prototype connections don't work like sign in? How can I switch screens?
